### ISSUE TITLE
about b+ tree serialize/deserialize

### ISSUE THREAD

**Issue by songhtdo** [tlx/tlx#15]
Hello! 
I see now btree serialization and deserialization function was cancelled, you can add?

**Comment by bingmann** [comment]
Hmm, I can't remember the reason I removed them. Probably just didn't have the time to fix them, or considered them unnecessary.
I think the reason was that the previous serialization didn't really work with non-POD types.
If you need it, maybe write a patch and pull request.
One probably wants an interface with non-POD <-> Byte serializers

**Comment by songhtdo** [comment]
OK, thanks.
